version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: galileoio_bot
      DB_PASSWORD: 1234
      DB_NAME: galileoio_bot
      DB_HOST: localhost
      DB_PORT: 5684
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: galileoio_bot
      POSTGRES_USER: galileoio_bot
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galileoio_bot"]
      timeout: 20s
      retries: 10
volumes:
  db-data:
